# Generated by Django 5.2.14 on 2026-06-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='department',
            field=models.CharField(choices=[('computer', 'Computer Science'), ('civil', 'Civil Engineering'), ('architecture', 'Architecture'), ('electronics', 'Electronics Engineering'), ('mechanical', 'Mechanical Engineering'), ('electrical', 'Electrical Engineering'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
