# Generated by Django 5.2.14 on 2026-06-26 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assignment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='target_audience',
            field=models.CharField(choices=[('all', 'All Students'), ('section_a', 'Section A Only'), ('section_b', 'Section B Only'), ('section_c', 'Section C Only'), ('section_d', 'Section D Only')], default='all', max_length=20),
        ),
    ]
