# Generated by Django 5.2.14 on 2026-06-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
