# Generated by Django 5.2.14 on 2026-07-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='batch',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='department',
            field=models.CharField(choices=[('computer', 'BE Computer'), ('civil', 'BE Civil'), ('architecture', 'BE Architecture'), ('electronics', 'BE Electronics'), ('mechanical', 'BE IT'), ('electrical', 'BE Electrical'), ('general', 'General')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('announcement', 'Announcement'), ('assignment', 'Assignment')], max_length=20),
        ),
    ]
